const { Level } = require("level");
const db1 = new Level("./db1");
const db2 = new Level("./db2");

db1.put("1", "Cambiago", function (error) {});
db1.put("2", "Saintes", function (error) {});
db1.put("3", "Bhubaneswar", function (error) {});
db1.put("4", "B.S.D.", function (error) {});
db1.put("5", "Dover", function (error) {});
db1.put("6", "Moorsele", function (error) {});
db1.put("7", "Tulsa", function (error) {});
db1.put("8", "Kungälv", function (error) {});
db1.put("9", "Eugene", function (error) {});
db1.put("10", "Linlithgow", function (error) {});
db1.put("11", "Chiniot", function (error) {});
db1.put("12", "Cinco Esquinas", function (error) {});
db1.put("13", "Juazeiro doNorte", function (error) {});
db1.put("14", "Bothey", function (error) {});
db1.put("15", "Shreveport", function (error) {});
db1.put("16", "Pulderbos", function (error) {});
db1.put("17", "Nagpur", function (error) {});
db1.put("18", "Saint-Prime", function (error) {});
db1.put("19", "Ucluelet", function (error) {});
db1.put("20", "Luton", function (error) {});
db1.put("21", "Alma", function (error) {});
db1.put("22", "Casalbuono", function (error) {});
db1.put("23", "Raipur", function (error) {});
db1.put("24", "Saguenay", function (error) {});
db1.put("25", "Navsari", function (error) {});
db1.put("26", "Suxy", function (error) {});
db1.put("27", "Les Bons Villers ", function (error) {});
db1.put("28", "Tiruvottiyur", function (error) {});
db1.put("29", "Treppo Carnico ", function (error) {});
db1.put("30", "Dro", function (error) {});
db1.put("31", "Zwettl-Niederösterreich", function (error) {});
db1.put("32", "Nampa", function (error) {});
db1.put("33", "Heusweiler", function (error) {});
db1.put("34", "Teralfene", function (error) {});
db1.put("35", "Guardia Sanframondi", function (error) {});
db1.put("36", "San Pablo", function (error) {});
db1.put("37", "Fraser-Fort George", function (error) {});
db1.put("38", "Frankfort", function (error) {});
db1.put("39", "Brechin", function (error) {});
db1.put("40", "Ayr", function (error) {});
db1.put("41", "Duncan", function (error) {});
db1.put("42", "Morolo", function (error) {});
db1.put("43", "Linz", function (error) {});
db1.put("44", "Pune", function (error) {});
db1.put("45", "Chandrapur", function (error) {});
db1.put("46", "Annapolis Royal", function (error) {});
db1.put("47", "Miami", function (error) {});
db1.put("48", "Lowestoft", function (error) {});
db1.put("49", "Green Bay", function (error) {});
db1.put("50", "Neu-Ulm", function (error) {});
db1.put("51", "Meix-Devant-Virton", function (error) {});
db1.put("52", "Flint", function (error) {});
db1.put("53", "Mobile", function (error) {});
db1.put("54", "Terlago", function (error) {});
db1.put("55", "Lehrte", function (error) {});
db1.put("56", "Beaconsfield", function (error) {});
db1.put("57", "Huissen", function (error) {});
db1.put("58", "Fortune", function (error) {});
db1.put("59", "Malbaie", function (error) {});
db1.put("60", "Wells", function (error) {});
db1.put("61", "Caprino Bergamasco", function (error) {});
db1.put("62", "Llandrindod Wells", function (error) {});
db1.put("63", "Westrem", function (error) {});
db1.put("64", "Kraków", function (error) {});
db1.put("65", "Auckland", function (error) {});
db1.put("66", "Jonesboro", function (error) {});
db1.put("67", "WagnelŽe", function (error) {});
db1.put("68", "Blankenberge", function (error) {});
db1.put("69", "Uyo", function (error) {});
db1.put("70", "Wunstorf", function (error) {});
db1.put("71", "Molina", function (error) {});
db1.put("72", "Hohenems", function (error) {});
db1.put("73", "Åkersberga", function (error) {});
db1.put("74", "Denver", function (error) {});
db1.put("75", "Hoyerswerda", function (error) {});
db1.put("76", "Madrid", function (error) {});
db1.put("77", "Juneau", function (error) {});
db1.put("78", "Porto Cesareo", function (error) {});
db1.put("79", "Ongole", function (error) {});
db1.put("80", "Jammu", function (error) {});
db1.put("81", "Neuss", function (error) {});
db1.put("82", "Hull", function (error) {});
db1.put("83", "Kolkata", function (error) {});
db1.put("84", "Ludhiana", function (error) {});
db1.put("85", "San Clemente", function (error) {});
db1.put("86", "Newport News", function (error) {});
db1.put("87", "Vieux-Genappe", function (error) {});
db1.put("88", "Tierra Amarilla", function (error) {});
db1.put("89", "Cajazeiras", function (error) {});
db1.put("90", "Accadia", function (error) {});
db1.put("91", "Pickering", function (error) {});
db1.put("92", "Shawinigan", function (error) {});
db1.put("93", "Anchorage", function (error) {});
db1.put("94", "Aurora", function (error) {});
db1.put("95", "Lakewood", function (error) {});
db1.put("96", "Juneau", function (error) {});
db1.put("97", "Cape Breton Island", function (error) {});
db1.put("98", "Rewa", function (error) {});
db1.put("99", "Kerkrade", function (error) {});
db1.put("100", "Bridgeport", function (error) {});

db2.put("101", "Nedlands", function (error) {});
db2.put("102", "MabomprŽ", function (error) {});
db2.put("103", "Langenburg", function (error) {});
db2.put("104", "Edmonton", function (error) {});
db2.put("105", "Villers-sur-Semois", function (error) {});
db2.put("106", "Lac-Serent", function (error) {});
db2.put("107", "Hartlepool", function (error) {});
db2.put("108", "Salzburg", function (error) {});
db2.put("109", "LiŽge", function (error) {});
db2.put("110", "Chaudfontaine", function (error) {});
db2.put("111", "Córdoba", function (error) {});
db2.put("112", "Fort Simpson", function (error) {});
db2.put("113", "Les Bulles", function (error) {});
db2.put("114", "New Westminster", function (error) {});
db2.put("115", "ZŽtrud-Lumay", function (error) {});
db2.put("116", "Mayerthorpe", function (error) {});
db2.put("117", "Avellino", function (error) {});
db2.put("118", "Des Moines", function (error) {});
db2.put("119", "Harrison Hot Springs", function (error) {});
db2.put("120", "Linares", function (error) {});
db2.put("121", "Boston", function (error) {});
db2.put("122", "Chetwynd", function (error) {});
db2.put("123", "Gijón", function (error) {});
db2.put("124", "Llanidloes", function (error) {});
db2.put("125", "Hove", function (error) {});
db2.put("126", "Drachten", function (error) {});
db2.put("127", "Rocca di Cambio", function (error) {});
db2.put("128", "Wuppertal", function (error) {});
db2.put("129", "Pepingen", function (error) {});
db2.put("130", "Suxy", function (error) {});
db2.put("131", "Retford", function (error) {});
db2.put("132", "Lesve", function (error) {});
db2.put("133", "Scalloway", function (error) {});
db2.put("134", "Badalona", function (error) {});
db2.put("135", "Vaux-lez-Rosieres", function (error) {});
db2.put("136", "Siracusa", function (error) {});
db2.put("137", "Williams Lake", function (error) {});
db2.put("138", "Moose Jaw", function (error) {});
db2.put("139", "Wokingham", function (error) {});
db2.put("140", "Aurangabad", function (error) {});
db2.put("141", "Barranca", function (error) {});
db2.put("142", "Adria", function (error) {});
db2.put("143", "Malgesso", function (error) {});
db2.put("144", "Sant'Eusanio Forconese", function (error) {});
db2.put("145", "Fuenlabrada", function (error) {});
db2.put("146", "Swansea", function (error) {});
db2.put("147", "Aylesbury", function (error) {});
db2.put("148", "Celle", function (error) {});
db2.put("149", "Eigenbrakel", function (error) {});
db2.put("150", "Paglieta", function (error) {});
db2.put("151", "Vollezele", function (error) {});
db2.put("152", "Gonda", function (error) {});
db2.put("153", "Flint", function (error) {});
db2.put("154", "Sevilla", function (error) {});
db2.put("155", "TrognŽe", function (error) {});
db2.put("156", "Sant'Angelo a Cupolo", function (error) {});
db2.put("157", "Callander", function (error) {});
db2.put("158", "Auburn", function (error) {});
db2.put("159", "Malloa", function (error) {});
db2.put("160", "Brye", function (error) {});
db2.put("161", "Assen", function (error) {});
db2.put("162", "Whitchurch-Stouffville", function (error) {});
db2.put("163", "Allentown", function (error) {});
db2.put("164", "Lagundo/Algund", function (error) {});
db2.put("165", "Alto del Carmen", function (error) {});
db2.put("166", "Burhaniye", function (error) {});
db2.put("167", "Lichfield", function (error) {});
db2.put("168", "Tarzo", function (error) {});
db2.put("169", "Baisy-Thy", function (error) {});
db2.put("170", "Ourense", function (error) {});
db2.put("171", "Talence", function (error) {});
db2.put("172", "A Coruña", function (error) {});
db2.put("173", "Houtain-le-Val", function (error) {});
db2.put("174", "Montpellier", function (error) {});
db2.put("175", "Hamme", function (error) {});
db2.put("176", "Hérouville-Saint-Clair", function (error) {});
db2.put("177", "Wemmel", function (error) {});
db2.put("178", "Widooie", function (error) {});
db2.put("179", "Tuscaloosa", function (error) {});
db2.put("180", "Lincoln", function (error) {});
db2.put("181", "Keiem", function (error) {});
db2.put("182", "Erpion", function (error) {});
db2.put("183", "Araban", function (error) {});
db2.put("184", "Falkirk", function (error) {});
db2.put("185", "Tiruvannamalai", function (error) {});
db2.put("186", "Port Alice", function (error) {});
db2.put("187", "Paine", function (error) {});
db2.put("188", "Saint-Martin", function (error) {});
db2.put("189", "Schagen", function (error) {});
db2.put("190", "Fort Resolution", function (error) {});
db2.put("191", "Pfungstadt", function (error) {});
db2.put("192", "Chestermere", function (error) {});
db2.put("193", "Bienne-lez-Happart", function (error) {});
db2.put("194", "Swadlincote", function (error) {});
db2.put("195", "Limena", function (error) {});
db2.put("196", "Rouvroy", function (error) {});
db2.put("197", "Arauco", function (error) {});
db2.put("198", "IJlst", function (error) {});
db2.put("199", "Laino Castello", function (error) {});
db2.put("200", "Westkerke", function (error) {});
